// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHP33-crmjqYuJE3oF535YBXorl4vv5lQ',
    appId: '1:208780582743:web:1321f29afa29481a7ea812',
    messagingSenderId: '208780582743',
    projectId: 'final-cb1a0',
    authDomain: 'final-cb1a0.firebaseapp.com',
    storageBucket: 'final-cb1a0.appspot.com',
    measurementId: 'G-W0Q5N74BRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhyvvFiShoeASGu4CYbJFkobpoCGgF6o4',
    appId: '1:208780582743:android:4c92d0605ca986dd7ea812',
    messagingSenderId: '208780582743',
    projectId: 'final-cb1a0',
    storageBucket: 'final-cb1a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjYyW-cZ42dAeHTwfrft2Bojcz-eo0RA',
    appId: '1:208780582743:ios:eba06822bb49021c7ea812',
    messagingSenderId: '208780582743',
    projectId: 'final-cb1a0',
    storageBucket: 'final-cb1a0.appspot.com',
    androidClientId: '208780582743-3kkf5qol4liqrqa1j6tvgv9qjkba2emp.apps.googleusercontent.com',
    iosClientId: '208780582743-ahh39vlcejefhjtc5m1vo6ovamll38en.apps.googleusercontent.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjYyW-cZ42dAeHTwfrft2Bojcz-eo0RA',
    appId: '1:208780582743:ios:eba06822bb49021c7ea812',
    messagingSenderId: '208780582743',
    projectId: 'final-cb1a0',
    storageBucket: 'final-cb1a0.appspot.com',
    androidClientId: '208780582743-3kkf5qol4liqrqa1j6tvgv9qjkba2emp.apps.googleusercontent.com',
    iosClientId: '208780582743-ahh39vlcejefhjtc5m1vo6ovamll38en.apps.googleusercontent.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHP33-crmjqYuJE3oF535YBXorl4vv5lQ',
    appId: '1:208780582743:web:3084c53cf617a0db7ea812',
    messagingSenderId: '208780582743',
    projectId: 'final-cb1a0',
    authDomain: 'final-cb1a0.firebaseapp.com',
    storageBucket: 'final-cb1a0.appspot.com',
    measurementId: 'G-2STWVVVGNG',
  );
}
